### PR TITLE
Prep for Composer and Packagist

### PR DESCRIPTION
**Pull request by mcordingley**
Adding the boilerplate to be able to use this through Composer.

### CODE REVIEW

**Comment by mcordingley** [comment]
Nudge. I can send the OOP wrapper as a pull request once you've accepted this. Quit with this "paid work" thing, you need to work on this library!

**Comment by anthonybennett** [comment]
Life. Work, and had the baby, and then she was in the hospital with a
virus. (She's fine and back home now.)

_sigh_ I will get back to this. I promise.

**Comment by mcordingley** [comment]
Congratulations on the daughter!

On Sun, Sep 1, 2013 at 7:23 PM, anthonybennett notifications@github.comwrote:

> Life. Work, and had the baby, and then she was in the hospital with a
> virus. (She's fine and back home now.)
> 
> _sigh_ I will get back to this. I promise.
> 
> On Mon, Aug 26, 2013 at 12:16 PM, Michael Cordingley <
> notifications@github.com> wrote:
> 
> > Nudge. I can send the OOP wrapper as a pull request once you've accepted
> > this. Quit with this "paid work" thing, you need to work on this
> > library!
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/anthonybennett/underscore.php/pull/1#issuecomment-23274944>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/anthonybennett/underscore.php/pull/1#issuecomment-23635365
> .

## 

Michael Cordingley
740.707.7809

**Comment by mcordingley** [comment]
I offer the bribe of a glass of Woodford.

**Pull request closed without merging**
